<a href="https://colab.research.google.com/github/alfxer69/TemasPythonEjercicios/blob/main/notebooks/single-point-regression-gradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gradiente de una regresión de un solo punto

En este cuaderno, calculamos el gradiente del coste cuadrático con respecto a los parámetros de un modelo de regresión en línea recta. Mantenemos las derivadas parciales lo más simples posible limitando el modelo al manejo de un único punto de datos.

In [ ]:
import torch

Usemos los mismos datos que usamos en el cuaderno [*Regresión en PyTorch*](https://github.com/joanby/matematicas-ml/blob/master/notebooks/regression-in-pytorch.ipynb) así como para demostrar la Pseudoinversa de Moore-Penrose en el cuaderno [*Álgebra Lineal II*](https://github.com/joanby/matematicas-ml/blob/master/notebooks/2-linear-algebra-ii.ipynb):

In [ ]:
xs = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7.])

In [ ]:
ys = torch.tensor([1.86, 1.31, .62, .33, .09, -.67, -1.23, -1.37])

La pendiente de la recta viene dada por $y = mx + b$:

In [ ]:
def regression(my_x, my_m, my_b):
    return my_m*my_x + my_b

Inicialicemos $m$ y $b$ con los mismos valores «aleatorios» cercanos a cero que hicimos en el cuaderno *Regresión en PyTorch*:

In [ ]:
m = torch.tensor([0.9]).requires_grad_()

In [ ]:
b = torch.tensor([0.1]).requires_grad_()

Para mantener las derivadas parciales lo más simple posible, vamos a avanzar con una sola instancia $i$ de los ocho posibles puntos de datos:

In [ ]:
i = 7
x = xs[i]
y = ys[i]

In [ ]:
x

tensor(7.)

In [ ]:
y

tensor(-1.3700)

**Paso 1**: Paso hacia adelante

Podemos fluir el tensor escalar $x$ a través de nuestro modelo de regresión para producir $\hat{y}$, una estimación de $y$. Antes de cualquier modelo de formación, se trata de una estimación arbitraria:

In [ ]:
yhat = regression(x, m, b)
yhat

tensor([6.4000], grad_fn=<AddBackward0>)

**Paso 2**: Comparar $\hat{y}$ con el valor real de $y$ para calcular el coste $C$

En el cuaderno *Regresión en PyTorch*, usamos el error cuadrático medio, que promedia el coste cuadrático sobre múltiples puntos de datos. Con un único punto de datos, aquí podemos usar sólo el coste cuadrático. Se define por: $$ C = (\hat{y} - y)^2 $$

In [ ]:
def squared_error(my_yhat, my_y):
    return (my_yhat - my_y)**2

In [ ]:
C = squared_error(yhat, y)
C

tensor([60.3729], grad_fn=<PowBackward0>)

**Paso 3**: Utilizar autodiff para calcular el gradiente de $C$ en función de los parámetros

In [ ]:
C.backward()

La derivada parcial de $C$ Con respecto a $m$ ($\frac{\partial C}{\partial m}$) es:

In [ ]:
m.grad

tensor([108.7800])

Y la derivada parcial de $C$ con respecto a $b$ ($\frac{\partial C}{\partial b}$) es:

In [ ]:
b.grad

tensor([15.5400])

Volver a las diapositivas de *Cálculo II*  aquí para derivar $\frac{\partial C}{\partial m}$ y $\frac{\partial C}{\partial b}$.**

$$ \frac{\partial C}{\partial m} = 2x(\hat{y} - y) $$

In [ ]:
2*x*(yhat.item()-y)

tensor(108.7800)

$$ \frac{\partial C}{\partial b} = 2(\hat{y}-y) $$

In [ ]:
2*(yhat.item()-y)

tensor(15.5400)

### El gradiente del Coste, $\nabla C$

El gradiente del coste, que se simboliza $\nabla C$ (pronunciado «nabla C»), es un vector de todas las derivadas parciales de $C$ con respecto a cada uno de los parámetros individuales del modelo:

$\nabla C = \nabla_p C = \left[ \frac{\partial{C}}{\partial{p_1}}, \frac{\partial{C}}{\partial{p_2}}, \cdots, \frac{\partial{C}}{\partial{p_n}} \right]^T $

En este caso, sólo hay dos parámetros, $b$ y $m$:

$\nabla C = \left[ \frac{\partial{C}}{\partial{b}}, \frac{\partial{C}}{\partial{m}} \right]^T $

In [ ]:
gradient = torch.tensor([[b.grad.item(), m.grad.item()]]).T
gradient

tensor([[ 15.5400],
        [108.7800]])